###
POST http://localhost:8000/api-v1/user/register
Content-Type: application/json

{
    "firstName": "Ban",
    "lastName": "Tran",
    "email": "trannhatban34@gmail.com",
    "password": "abc123"
}

###
POST http://localhost:8000/api-v1/user/login
Content-Type: application/json

{
    "email": "TrannhatBan4123@gmail.com",
    "password": "abc123"
}
###

GET  http://localhost:8000/api-v1/user/list-users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2VlZTVlOWI3NDFjYTRiNTJiY2I5YzciLCJpYXQiOjE2NzY2MDA5MDEsImV4cCI6MTY3NjYwMTgwMX0.NYbGzTrc0K0sCv1Zqpi-MyyZbZV9-Do802eFzLR0Zf0

###
POST http://localhost:8000/api-v1/user/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2ViMTI5ZWI5NmZmYmQ1NTUwZjYyNzciLCJpYXQiOjE2NzY1OTkxOTMsImV4cCI6MTcwODE1Njc5M30.DVEYrmAWYvQoKSSUCQVxCUfMQAK-Brbf7twxoW__dpQ"
}

###
DELETE http://localhost:8000/api-v1/user/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2M2VlZTVlOWI3NDFjYTRiNTJiY2I5YzciLCJpYXQiOjE2NzY2MDM2MTQsImV4cCI6MTcwODE2MTIxNH0.B63w8InZVoJdkUXnt2QpUj3eWMHboqgXAjFCwB8kOiQ"
}

###Regiter typeom mysql
POST http://localhost:8000/api-v1/user/register-typeorm
Content-Type: application/json

{
    "firstName": "Trần",
    "lastName": "A",
    "email": "tranA@gmail.com",
    "password": "abc123"
}

###Login typeom mysql
POST http://localhost:8000/api-v1/user/login-typeorm
Content-Type: application/json

{
    "email": "tranA@gmail.com",
    "password": "abc123"
}

###Refresh token typeom mysql
POST http://localhost:8000/api-v1/user/refresh-token-typeorm
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5YWFlZmI2Mi02MDBjLTQxMTctOGZmYi04YTZhNjZlMGE4M2YiLCJpYXQiOjE2NzY2MDIwOTYsImV4cCI6MTcwODE1OTY5Nn0.GfDo2lrW93wEovniFdOQ9iZ8Mgs1dqdBXRMxMYD87tU"
}

###Logout typeom mysql
DELETE http://localhost:8000/api-v1/user/logout-typeorm
Content-Type: application/json

{
     "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5YWFlZmI2Mi02MDBjLTQxMTctOGZmYi04YTZhNjZlMGE4M2YiLCJpYXQiOjE2NzY2MDIxMjIsImV4cCI6MTcwODE1OTcyMn0.JF0ANlwnCYn3Yg-2X9GpwiEwz4pIjABCCqpop40Kdm4"
}

###Get list user typeorm mysql
GET http://localhost:8000/api-v1/user/list-users-typeorm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI5YWFlZmI2Mi02MDBjLTQxMTctOGZmYi04YTZhNjZlMGE4M2YiLCJpYXQiOjE2NzY2MDI3MTAsImV4cCI6MTY3NjYwMzYxMH0.pRpgTLnXBTWfAXBCYFTtBtXe_1SGy_2_py4LvTi_sPQ


###RESTFUL api
POST http://localhost:8000/api-v1/voucher/createVoucher
Content-Type: application/json

{
    "title": "Giảm giá khuyến mãi ngày valentine 1",
    "content": "Ok",
    "description": "Ok",
    "discount": "1233",
    "quantity": 12,
    "startTimeAt": "2023-02-20 17:42",
    "endTimeAt": "2023-02-20 23:23",
    "isInactive": "true",
    "isDelete": "false"
}

###RESTFUL api
POST http://localhost:8000/api-v1/voucher/create-voucher
Content-Type: application/json

{
    "title": "Giam gia khuyen mai",
    "content": "Ok",
    "description": "Ok",
    "discount": "1233",
    "quantity": 12,
    "startTimeAt": "16-02-2023 10:23",
    "endTimeAt": "16-02-2023 23:23",
    "isInactive": "true",
    "isDelete": "false",
    "hackchetmema": "Ok"
}

###
GET http://localhost:8000/api-v1/voucher/read-list-voucher

###
GET http://localhost:8000/api-v1/voucher/read-one-voucher/1bcac2be-fde7-4e74-bb44-89fc2f50e85b

###
PUT http://localhost:8000/api-v1/voucher/update-voucher/
Content-Type: application/json

{
    "id": "1bcac2be-fde7-4e74-bb44-89fc2f50e85b",
    "title": "Giam gia khuyen mai ngày 16-2-2023",
    "content": "Ok",
    "description": "Ok",
    "discount": 1233,
    "quantity": 12,
    "startTimeAt": "16-02-2023 10:23",
    "endTimeAt": "16-02-2023 23:23",
    "isInactive": "false",
    "isDelete": "false"
}

###
DELETE http://localhost:8000/api-v1/voucher/delete-voucher/
Content-Type: application/json

{
    "id": "1bcac2be-fde7-4e74-bb44-89fc2f50e85b"
}


